version: '3'
services:
  app:
    build: .
    volumes:
      - .:/src
    container_name: docker-node-tut
    restart: always
    ports:
      - 4026:8080
    command: bash -c /src/start.sh
    env_file: .env