version: '3'
services: 
    frontend:
        build: .
        container_name: MINBIL_C
        ports:
          - "3000:3000"
        # volumes:
        #   - ./MINBIL-V1:/app
        #   - ./app/node_modules
        stdin_open: true
        tty: true

